name: Trigger Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟触发一次

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API
        run: |
          curl -X POST "https://your-vercel-url/api/monitor" \
          -H "x-auth-token: ${{ secrets.AUTH_TOKEN }}" 